from __future__ import annotations

import json
import uuid
from dataclasses import asdict, dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Any

from agentx.config import Settings


@dataclass
class LearningProposal:
    """A structured proposal for self-improvement / learning outcome."""
    id: str = field(default_factory=lambda: str(uuid.uuid4())[:8])
    timestamp: str = field(default_factory=lambda: datetime.now().isoformat())
    source: str = ""  # e.g. session_id, task_id, recovery
    lesson_type: str = ""  # prompt_improvement, recovery_strategy, agentyx_md_update, task_template, tool_usage_pattern
    title: str = ""
    description: str = ""
    evidence: list[str] = field(default_factory=list)  # quotes from transcript, error logs, success metrics
    proposed_change: str = ""  # concrete diff, new text, or instruction for edit
    fitness: dict[str, Any] = field(default_factory=dict)  # e.g. {"tests_pass": true, "ruff_ok": true, "no_principle_drift": true, "notes": "..."}
    status: str = "proposed"  # proposed, under_review, approved, applied, rejected
    applied_to: list[str] = field(default_factory=list)  # e.g. ["AGENTX.md:123", "recovery.py"]


class LearningManager:
    """
    Self-learning / improvement manager for agentX (inspired by ai-tetsu #3 learning loop + AGENTX.md self-mod protocol).

    - Always proposal-only for core changes.
    - Human (or explicit /approve) gate before applying to AGENTX.md or persistent state.
    - Records proposals in .agentx/learning/proposals/ (md + json for machine).
    - Can be triggered from AgentSession after ask/run, or via /learn command.
    - Integrates with MemoryHall for episodes if available.
    - Fitness checks encourage "smarter" proposals (pass tests, respect principles in AGENTX.md).
    """

    def __init__(self, settings: Settings, memory: Any = None):
        self.settings = settings
        self.workspace = settings.workspace
        self.memory = memory  # MemoryHallClient if available
        self.proposals_dir = self.workspace / ".agentx" / "learning" / "proposals"
        self.proposals_dir.mkdir(parents=True, exist_ok=True)
        self._index_path = self.proposals_dir / "index.json"
        self._load_index()

    def _load_index(self):
        if self._index_path.exists():
            with open(self._index_path, "r", encoding="utf-8") as f:
                self.index = json.load(f)
        else:
            self.index = {"proposals": []}

    def _save_index(self):
        with open(self._index_path, "w", encoding="utf-8") as f:
            json.dump(self.index, f, indent=2, ensure_ascii=False)

    def propose(self, proposal: LearningProposal) -> Path:
        """Write a new proposal. Returns the path to the proposal file."""
        # Basic fitness default
        if not proposal.fitness:
            proposal.fitness = {
                "ruff_ok": None,
                "tests_relevant_pass": None,
                "respects_agentyx_md_principles": None,  # agent should have checked AGENTX.md
                "evidence_based": len(proposal.evidence) > 0,
            }

        # Write JSON for machine readability
        json_path = self.proposals_dir / f"{proposal.timestamp[:10]}-{proposal.id}.json"
        with open(json_path, "w", encoding="utf-8") as f:
            json.dump(asdict(proposal), f, indent=2, ensure_ascii=False, default=str)

        # Write human-readable MD
        md_path = self.proposals_dir / f"{proposal.timestamp[:10]}-{proposal.id}.md"
        md_content = f"""# Learning Proposal {proposal.id}

**Timestamp**: {proposal.timestamp}
**Source**: {proposal.source}
**Type**: {proposal.lesson_type}
**Status**: {proposal.status}

## Title
{proposal.title}

## Description
{proposal.description}

## Evidence
{chr(10).join(f"- {e}" for e in proposal.evidence) or "(none provided)"}

## Proposed Change
```
{proposal.proposed_change}
```

## Fitness
```json
{json.dumps(proposal.fitness, indent=2, ensure_ascii=False)}
```

## Applied To
{chr(10).join(f"- {a}" for a in proposal.applied_to) or "(not yet applied)"}

---
*Generated by agentX self-learning loop. Review and approve before applying to core (AGENTX.md, prompts, recovery, etc.). See AGENTX.md § Self-Improvement & Modification Protocol.*
"""
        with open(md_path, "w", encoding="utf-8") as f:
            f.write(md_content)

        # Update index
        self.index["proposals"].append({
            "id": proposal.id,
            "timestamp": proposal.timestamp,
            "type": proposal.lesson_type,
            "status": proposal.status,
            "title": proposal.title,
            "json": str(json_path.relative_to(self.workspace)),
            "md": str(md_path.relative_to(self.workspace)),
        })
        self._save_index()

        # Optionally write to Memory Hall as learning episode
        if self.memory:
            try:
                self.memory.write(
                    f"Learning proposal {proposal.id}: {proposal.title}\n{proposal.description}\nEvidence: {proposal.evidence}",
                    namespace=self.settings.namespace or "project:agentX",
                )
            except Exception:
                pass  # non-fatal

        return md_path

    def list_proposals(self, status: str | None = None) -> list[dict]:
        """List proposals, optionally filtered by status."""
        if status:
            return [p for p in self.index.get("proposals", []) if p.get("status") == status]
        return self.index.get("proposals", [])

    def get_proposal(self, proposal_id: str) -> LearningProposal | None:
        for p in self.index.get("proposals", []):
            if p["id"] == proposal_id:
                json_path = self.workspace / p["json"]
                if json_path.exists():
                    with open(json_path, "r", encoding="utf-8") as f:
                        data = json.load(f)
                    return LearningProposal(**data)
        return None

    def update_status(self, proposal_id: str, new_status: str, applied_to: list[str] | None = None) -> bool:
        """Update a proposal's status (e.g. after human review). For core applies, use with care per AGENTX.md protocol."""
        for p in self.index.get("proposals", []):
            if p["id"] == proposal_id:
                p["status"] = new_status
                if applied_to:
                    p["applied_to"] = applied_to
                self._save_index()

                # Sync back to JSON
                prop = self.get_proposal(proposal_id)
                if prop:
                    prop.status = new_status
                    if applied_to:
                        prop.applied_to = applied_to
                    json_path = self.workspace / p["json"]
                    with open(json_path, "w", encoding="utf-8") as f:
                        json.dump(asdict(prop), f, indent=2, ensure_ascii=False, default=str)
                return True
        return False

    def reflect_on_session(
        self,
        ollama: Any,
        session_transcript: str,
        recent_errors: list[dict],
        task_outcomes: list[dict],
        current_agentyx_md_principles: str,
    ) -> list[LearningProposal]:
        """
        Use LLM to reflex and generate learning proposals from a session.
        This makes the agent 'smarter' over time by extracting reusable lessons.
        Always returns proposals (human gate later).
        """
        prompt = f"""You are agentX reflecting on a completed session to improve yourself.

Session transcript summary:
{session_transcript[:8000]}

Recent errors/recoveries:
{json.dumps(recent_errors, ensure_ascii=False)[:2000]}

Task outcomes:
{json.dumps(task_outcomes, ensure_ascii=False)[:2000]}

Current core principles from AGENTX.md (do not violate these in proposals):
{current_agentyx_md_principles[:3000]}

Task: Extract 1-3 high-value, actionable learning proposals that would make future runs more reliable, efficient, or better aligned with principles.

For each proposal, output STRICT JSON (one object per proposal, no extra text):
{{
  "lesson_type": "prompt_improvement" | "recovery_strategy" | "agentyx_md_update" | "task_template" | "tool_usage_pattern",
  "title": "short title",
  "description": "why this helps + evidence from this session",
  "evidence": ["quote1", "outcome2", ...],
  "proposed_change": "concrete: e.g. 'Add this paragraph to AGENTX.md under Recovery' or 'In recovery playbook, add case for X: ...' or 'Update system prompt to always do Y after edit'",
  "fitness": {{"respects_agentyx_md_principles": true, "evidence_based": true, "notes": "..." }}
}}

Only propose things that are generalizable and would have helped in this session. Prioritize safety and fidelity to existing principles.
"""
        try:
            # Assume ollama has a simple chat or complete method; adapt to actual client
            response = ollama.chat([
                {"role": "system", "content": "You are a careful, evidence-based self-improvement module for agentX. Output only valid JSON array of proposals."},
                {"role": "user", "content": prompt}
            ], model=ollama.model if hasattr(ollama, 'model') else None)  # rough

            # Parse (robust parsing needed in real; here simplified)
            text = response.get("content", "[]") if isinstance(response, dict) else str(response)
            proposals_data = json.loads(text) if text.strip().startswith("[") else []
            if not isinstance(proposals_data, list):
                proposals_data = [proposals_data]

            results = []
            for data in proposals_data[:3]:  # cap
                prop = LearningProposal(
                    source="session_reflection",
                    lesson_type=data.get("lesson_type", "general"),
                    title=data.get("title", "Untitled lesson"),
                    description=data.get("description", ""),
                    evidence=data.get("evidence", []),
                    proposed_change=data.get("proposed_change", ""),
                    fitness=data.get("fitness", {}),
                )
                self.propose(prop)
                results.append(prop)
            return results
        except Exception as e:
            # Fallback: create a minimal proposal about the failure to learn
            fallback = LearningProposal(
                source="session_reflection",
                lesson_type="recovery_strategy",
                title="Learning reflection failed - improve error handling in learning",
                description=f"Reflexion LLM call failed: {e}. Future learning should be more robust.",
                evidence=[f"Error during reflect: {str(e)[:200]}"],
                proposed_change="Add better fallback and parsing in learning.py reflect_on_session. Consider using structured output tools.",
            )
            self.propose(fallback)
            return [fallback]


def load_learning_manager(settings: Settings, memory: Any = None) -> LearningManager:
    return LearningManager(settings, memory)
